# Generated by Django 5.1.1 on 2026-09-18 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='container_qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='latitude',
            field=models.FloatField(blank=True, default=19.076, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='longitude',
            field=models.FloatField(blank=True, default=72.8777, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='preferred_time_slot',
            field=models.CharField(default='Morning (09:00 - 12:00)', max_length=50),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='route_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='quantity_liters',
            field=models.FloatField(help_text='Estimated Quantity in Liters'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('CLUSTERED', 'Clustered'), ('ASSIGNED', 'Assigned to Collector'), ('IN_PROGRESS', 'Collector En Route'), ('COLLECTED', 'Verified & Collected'), ('AT_DEPOT', 'Received at Depot'), ('RECONCILED', 'Batch Reconciled'), ('SENT_TO_PROCESSOR', 'Dispatched to Processor'), ('COMPLETED', 'Converted to Biodiesel'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending (Requested)'), ('APPROVED', 'Approved (Assigned)')], default='REQUESTED', max_length=30),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('seal_number', models.CharField(blank=True, max_length=100)),
                ('expected_quantity_liters', models.FloatField(default=0.0)),
                ('received_quantity_liters', models.FloatField(default=0.0)),
                ('reconciliation_variance_liters', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DRAFT', 'Drafting Batch'), ('RECONCILED', 'Reconciled & Sealed at Depot'), ('DISPATCHED', 'Dispatched to Processor'), ('RECEIVED_BY_PROCESSOR', 'Received by Processor'), ('PROCESSED', 'Converted to Biodiesel'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('depot_notes', models.TextField(blank=True)),
                ('processor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot_batches', to=settings.AUTH_USER_MODEL)),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('stage', models.CharField(choices=[('GENERATION', 'UCO Generation'), ('CLUSTERING', 'Clustering & Routing'), ('COLLECTION', 'Collector Verification'), ('DEPOT', 'Depot Reconciliation'), ('PROCESSING', 'Biodiesel Processing')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='myapp.pickuprequest')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='myapp.batch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiodieselConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uco_input_liters', models.FloatField()),
                ('biodiesel_output_liters', models.FloatField()),
                ('glycerin_byproduct_kg', models.FloatField(default=0.0)),
                ('efficiency_percentage', models.FloatField(default=89.0, help_text='Conversion efficiency (88-92% prototype standard)')),
                ('tpc_tested_percentage', models.FloatField(default=27.5, help_text='Total Polar Compounds % (>25% complies with RUCO diversion)')),
                ('lab_notes', models.TextField(blank=True)),
                ('conversion_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion', to='myapp.batch')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisposalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('volume_liters', models.FloatField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('qr_verification_code', models.CharField(blank=True, max_length=100)),
                ('ruco_compliance_statement', models.TextField(default='This digital certificate certifies that the used cooking oil referenced has been collected, verified, and diverted from the human food chain into authorized biofuel/biodiesel production in accordance with FSSAI RUCO initiative guidelines.')),
                ('is_valid', models.BooleanField(default=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='myapp.pickuprequest')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('PICKUP', 'Pickup Status'), ('PAYMENT', 'Payment Payout'), ('BATCH', 'Batch Dispatch'), ('ALERT', 'Anomaly Alert'), ('SYSTEM', 'System Update')], default='PICKUP', max_length=30)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('liters', models.FloatField()),
                ('rate_per_liter', models.FloatField(default=50.0, help_text='RUCO baseline payout ₹/L')),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('PROCESSING', 'Processing Instant Payout'), ('PAID', 'Paid / Settled'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(default='UPI Instant Direct Settlement', max_length=50)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='myapp.pickuprequest')),
            ],
        ),
        migrations.CreateModel(
            name='PickupCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ASSIGNED', 'Assigned to Collector'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('center_latitude', models.FloatField(blank=True, default=19.076, null=True)),
                ('center_longitude', models.FloatField(blank=True, default=72.8777, null=True)),
                ('radius_km', models.FloatField(default=5.0, help_text='Micro-collection radius (e.g. 5 km)')),
                ('total_estimated_liters', models.FloatField(default=0.0)),
                ('total_collected_liters', models.FloatField(default=0.0)),
                ('route_optimized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clusters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='myapp.pickupcluster'),
        ),
        migrations.CreateModel(
            name='PickupVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_qr', models.CharField(max_length=100)),
                ('qr_verified', models.BooleanField(default=True)),
                ('verified_latitude', models.FloatField(blank=True, null=True)),
                ('verified_longitude', models.FloatField(blank=True, null=True)),
                ('gps_verified', models.BooleanField(default=True)),
                ('estimated_quantity_liters', models.FloatField()),
                ('verified_weight_liters', models.FloatField(help_text='Actual measured quantity in Liters')),
                ('discrepancy_liters', models.FloatField(default=0.0)),
                ('discrepancy_percent', models.FloatField(default=0.0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.TextField(blank=True)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='pickup_photos/')),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='myapp.pickuprequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Operations Tower'), ('GENERATOR', 'UCO Generator (Restaurant / Food Business)'), ('COLLECTOR', 'UCO Collector'), ('DEPOT', 'Depot Aggregator'), ('PROCESSOR', 'Authorized Biodiesel Processor')], default='GENERATOR', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, default=19.076, null=True)),
                ('longitude', models.FloatField(blank=True, default=72.8777, null=True)),
                ('fssai_license', models.CharField(blank=True, help_text='FSSAI License / RUCO ID', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_liters', models.FloatField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.batch')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='myapp.pickuprequest')),
            ],
            options={
                'unique_together': {('batch', 'pickup')},
            },
        ),
    ]
