# Generated by Django 5.1.1 on 2026-09-18 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pickuprequest_collector_pickuprequest_contact_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude from browser GPS (-90 to 90)')),
                ('longitude', models.FloatField(help_text='Longitude from browser GPS (-180 to 180)')),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in metres (from browser Geolocation API)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True while collector has tracking enabled; False when stopped')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the GPS fix was captured on the device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.OneToOneField(help_text='The collector user this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gps_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
